---
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2

workflows:
  main:
    jobs:
      - hugo/build:
          asciidoc: true
          html-proofer: true
          htmlproofer-http-status-ignore: "'0,999'"
          htmlproofer-url-ignore: "'/ooi-toolkit-ds/'"
          htmlproofer-timeframe: "'6w'"
          hugo-extra-flags: "--minify"
          version: "latest"
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/ooi-toolkit-ds/public
    steps:
      # add repository deploy key (for pull/push access)
      - add_ssh_keys:
          fingerprints:
            - "92:53:b3:cb:93:19:50:a4:4b:e6:d9:09:ea:39:98:52"

      # deploy.sh dependencies
      - run: sudo apt-get update && sudo apt-get install -y rsync

      # clone repo (required to access `.circleci/deploy.sh`)
      - run: git clone --depth=1 https://github.com/unicef/ooi-toolkit-ds.git

      # checkout generated html
      - attach_workspace:
          at: ooi-toolkit-ds

      # deploy to production
      - deploy:
          name: Deploy to GitHub Pages
          command: ./ooi-toolkit-ds/.circleci/deploy.sh
